image: Visual Studio 2017

environment:
  matrix:
    - platform: x86
      QT5: C:\Qt\5.12.1\msvc2017
      VCVARS: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"'
    - platform: x64
      QT5: C:\Qt\5.12.1\msvc2017_64
      VCVARS: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"'

before_build:
  - set PATH=%QT5%\bin;%PATH%
  - call %VCVARS%
  - cd %APPVEYOR_BUILD_FOLDER%
  - qmake CONFIG+=unarr

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - nmake
